name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file core/Dockerfile --tag qq-farm-bot-ui:latest
        docker save qq-farm-bot-ui:latest -o qq-farm-bot-ui.tar
    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: qq-farm-bot-ui.tar
        retention-days: 7
